/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.itfac.bit.ui;

import com.itfac.bit.database.Database;
import java.awt.HeadlessException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.sql.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class DelResoNew extends javax.swing.JFrame {

    /**
     * Creates new form DelResoNew
     */
    Connection connection;
    PreparedStatement statement;
    ResultSet resultSet,resultSet1,resultSet2,resultSet3;
    String format;
    int abcd;
    DefaultListModel lm;
    DefaultTableModel tableModelEmployee, tableModelVehicle;
    MainNew mainNew;
    Boolean mainSelected = false;

    public DelResoNew() {
        initComponents();
        this.setResizable(false); 
        this.setLocationRelativeTo(null);
    }

    public DelResoNew(MainNew mainNew) {
        this.setResizable(false); 
        this.setLocationRelativeTo(null);
        this.mainNew = mainNew;
        initComponents();
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        Calendar cal = Calendar.getInstance();
        txt_date.setText(dateFormat.format(cal.getTime()));
        txt_date.setEditable(false);
        lm = new DefaultListModel();
        tableModelEmployee = (DefaultTableModel) table_employee.getModel();
        tableModelVehicle = (DefaultTableModel) table_vehicle.getModel();

        try {
            connection = Database.openConnection();
         
            statement = connection.prepareStatement("SELECT del_No FROM delivery_header");
            resultSet = statement.executeQuery();

            if (!resultSet.isBeforeFirst()) {
                format = String.format("%06d", 1);
            } else {
                resultSet.last();
                int delNo = resultSet.getInt(1);

                delNo = delNo + 1;
                format = String.format("%06d", delNo);
            }

            txt_deliveryNumber.setText(format);
            txt_deliveryNumber.setEditable(false);

            statement = connection.prepareStatement("SELECT ord_No FROM orders_header WHERE ord_Status='Placed' AND del_Req='Yes'");
            resultSet1 = statement.executeQuery();

            while (resultSet1.next()) {
                cmb_orderNumber.addItem(resultSet1.getString(1));
            }

            
            statement = connection.prepareStatement("SELECT emp_ID FROM delivery_representative_master WHERE dRep_Status='Available'");
            resultSet2 = statement.executeQuery();
            
            while (resultSet2.next()) {
                cmb_employeeID.addItem(resultSet2.getString(1));
            }

                
            statement = connection.prepareStatement("SELECT veh_No FROM vehicle_master WHERE veh_Status='Available'");
            resultSet3 = statement.executeQuery();
            
            while (resultSet3.next()) {
                cmb_vehicleNumber.addItem(resultSet3.getString(1));
            }

            cmb_orderNumber.setSelectedIndex(-1);
            cmb_employeeID.setSelectedIndex(-1);
            cmb_vehicleNumber.setSelectedIndex(-1);
            btn_removeOrderNumber.setEnabled(false);

            txt_firstName.setText("");
            txt_lastName.setText("");
            txt_contactNumber.setText("");
            cmb_employeeType.setText("");
            txt_brand.setText("");
            txt_model.setText("");
            txt_vehicleType.setText("");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error Occured.\n" + ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cmb_employeeID = new javax.swing.JComboBox();
        btn_addEmployee = new javax.swing.JButton();
        btn_removeEmployee = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_employee = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_contactNumber = new javax.swing.JTextField();
        txt_firstName = new javax.swing.JTextField();
        txt_lastName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmb_employeeType = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cmb_vehicleNumber = new javax.swing.JComboBox();
        btn_vehicleAdd = new javax.swing.JButton();
        btn_removeVehicle = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_vehicle = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_brand = new javax.swing.JTextField();
        txt_model = new javax.swing.JTextField();
        txt_vehicleType = new javax.swing.JTextField();
        btn_submit = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        cmb_orderNumber = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txt_date = new javax.swing.JTextField();
        txt_deliveryNumber = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        btn_addOrderNumber = new javax.swing.JButton();
        btn_removeOrderNumber = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(97, 212, 179));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delivery Resource Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 153));
        jLabel1.setText("Delivery Number");

        jPanel3.setBackground(new java.awt.Color(218, 247, 220));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delivery Representative Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        cmb_employeeID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_employeeIDItemStateChanged(evt);
            }
        });

        btn_addEmployee.setBackground(new java.awt.Color(0, 88, 50));
        btn_addEmployee.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_addEmployee.setForeground(java.awt.Color.white);
        btn_addEmployee.setText("Add");
        btn_addEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addEmployeeActionPerformed(evt);
            }
        });

        btn_removeEmployee.setBackground(new java.awt.Color(255, 103, 125));
        btn_removeEmployee.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_removeEmployee.setForeground(java.awt.Color.white);
        btn_removeEmployee.setText("Remove");
        btn_removeEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeEmployeeActionPerformed(evt);
            }
        });

        table_employee.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        table_employee.setForeground(new java.awt.Color(51, 102, 153));
        table_employee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "First Name", "Contact No", "Type"
            }
        ));
        jScrollPane4.setViewportView(table_employee);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 153));
        jLabel4.setText("Employee ID");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 102, 153));
        jLabel7.setText("Name");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 102, 153));
        jLabel9.setText("Contact Number");

        txt_contactNumber.setEditable(false);

        txt_firstName.setEditable(false);

        txt_lastName.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 102, 153));
        jLabel8.setText("Type");

        cmb_employeeType.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btn_addEmployee)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_removeEmployee))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_employeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txt_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_contactNumber)
                                .addComponent(cmb_employeeType, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(58, 58, 58))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_employeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_contactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_employeeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_addEmployee)
                    .addComponent(btn_removeEmployee))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(218, 247, 220));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vehicle Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 153));
        jLabel5.setText("Vehicle Number");

        cmb_vehicleNumber.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_vehicleNumberItemStateChanged(evt);
            }
        });

        btn_vehicleAdd.setBackground(new java.awt.Color(0, 88, 50));
        btn_vehicleAdd.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_vehicleAdd.setForeground(java.awt.Color.white);
        btn_vehicleAdd.setText("Add");
        btn_vehicleAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vehicleAddActionPerformed(evt);
            }
        });

        btn_removeVehicle.setBackground(new java.awt.Color(255, 103, 125));
        btn_removeVehicle.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_removeVehicle.setForeground(java.awt.Color.white);
        btn_removeVehicle.setText("Remove");
        btn_removeVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeVehicleActionPerformed(evt);
            }
        });

        table_vehicle.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        table_vehicle.setForeground(new java.awt.Color(51, 102, 153));
        table_vehicle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "Brand", "Model", "Type"
            }
        ));
        jScrollPane3.setViewportView(table_vehicle);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 102, 153));
        jLabel12.setText("Brand");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 102, 153));
        jLabel10.setText("Model");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 102, 153));
        jLabel11.setText("Type");

        txt_brand.setEditable(false);

        txt_model.setEditable(false);

        txt_vehicleType.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_brand)
                            .addComponent(cmb_vehicleNumber, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_model)
                            .addComponent(txt_vehicleType, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btn_vehicleAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_removeVehicle)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_vehicleNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_vehicleType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_vehicleAdd)
                    .addComponent(btn_removeVehicle))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_submit.setBackground(new java.awt.Color(0, 88, 50));
        btn_submit.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_submit.setForeground(java.awt.Color.white);
        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        btn_cancel.setBackground(new java.awt.Color(255, 103, 125));
        btn_cancel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_cancel.setForeground(java.awt.Color.white);
        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_clear.setBackground(new java.awt.Color(51, 102, 153));
        btn_clear.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_clear.setForeground(java.awt.Color.white);
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 153));
        jLabel2.setText("Date");

        txt_date.setEditable(false);

        jScrollPane1.setViewportView(jList1);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 153));
        jLabel3.setText("Order Number");

        btn_addOrderNumber.setBackground(new java.awt.Color(0, 88, 50));
        btn_addOrderNumber.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_addOrderNumber.setForeground(java.awt.Color.white);
        btn_addOrderNumber.setText("Add");
        btn_addOrderNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addOrderNumberActionPerformed(evt);
            }
        });

        btn_removeOrderNumber.setBackground(new java.awt.Color(255, 103, 125));
        btn_removeOrderNumber.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_removeOrderNumber.setForeground(java.awt.Color.white);
        btn_removeOrderNumber.setText("Remove");
        btn_removeOrderNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeOrderNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(btn_submit)
                .addGap(110, 110, 110)
                .addComponent(btn_cancel)
                .addGap(200, 200, 200))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_addOrderNumber)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cmb_orderNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_deliveryNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_removeOrderNumber))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_deliveryNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmb_orderNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_addOrderNumber)
                                    .addComponent(btn_removeOrderNumber)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_submit)
                    .addComponent(btn_clear)
                    .addComponent(btn_cancel))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_addOrderNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addOrderNumberActionPerformed
        if(cmb_orderNumber.getSelectedIndex() != -1) {
            String ordNo = String.valueOf(cmb_orderNumber.getSelectedItem());
            cmb_orderNumber.removeItem(ordNo);
            cmb_orderNumber.setSelectedIndex(-1);
            lm.addElement(ordNo);
            jList1.setModel(lm);
            int size = lm.getSize();

            if (size != 0) { //Nobody's left, disable firing.
                btn_removeOrderNumber.setEnabled(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please Select an Order Number", "ERROR", JOptionPane.ERROR_MESSAGE);
        }   
    }//GEN-LAST:event_btn_addOrderNumberActionPerformed

    private void btn_removeOrderNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeOrderNumberActionPerformed
        if (!jList1.isSelectionEmpty()) {
            String ordd = String.valueOf(jList1.getSelectedValue());
            int index = jList1.getSelectedIndex();
            lm.remove(index);
            cmb_orderNumber.addItem(ordd);
            int size = lm.getSize();

            if (size == 0) { //Nobody's left, disable firing.
                btn_removeOrderNumber.setEnabled(false);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please Select an Order Number from the List", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_removeOrderNumberActionPerformed

    private void cmb_employeeIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_employeeIDItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            String eID = String.valueOf(cmb_employeeID.getSelectedItem());

            try {
               
                statement = connection.prepareStatement("SELECT * FROM delivery_representative_master WHERE emp_ID=?");
                statement.setString(1, eID);
                resultSet = statement.executeQuery();
                
                if (resultSet.next()) {
                    txt_firstName.setText(resultSet.getString(2));
                    txt_lastName.setText(resultSet.getString(3));
                    txt_contactNumber.setText(String.valueOf(resultSet.getInt(5)));
                    cmb_employeeType.setText(resultSet.getString(6));

                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error Occured.\n" + ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_cmb_employeeIDItemStateChanged

    private void cmb_vehicleNumberItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_vehicleNumberItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            String vno = String.valueOf(cmb_vehicleNumber.getSelectedItem());

            try {
           
                statement = connection.prepareStatement("SELECT * FROM vehicle_master WHERE veh_No=?");
                statement.setString(1, vno);
                resultSet = statement.executeQuery();
                
                if (resultSet.next()) {
                    txt_brand.setText(resultSet.getString(2));
                    txt_model.setText(resultSet.getString(3));
                    txt_vehicleType.setText(resultSet.getString(4));
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error Occured.\n" + ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_cmb_vehicleNumberItemStateChanged

    private void btn_removeEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeEmployeeActionPerformed
        if (table_employee.getSelectedRow() != -1) {
            if (table_employee.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Table is Empty", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                String value = String.valueOf(table_employee.getValueAt(0, 0));
                tableModelEmployee.removeRow(table_employee.getSelectedRow());
                cmb_employeeID.addItem(value);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please Select a Row", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_removeEmployeeActionPerformed

    private void btn_removeVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeVehicleActionPerformed
        if (table_vehicle.getSelectedRow() != -1) {
            if (table_vehicle.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Table is Empty", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                String value = String.valueOf(table_vehicle.getValueAt(0, 0));
                tableModelVehicle.removeRow(table_vehicle.getSelectedRow());
                cmb_vehicleNumber.addItem(value);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please Select a Row", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_removeVehicleActionPerformed

    private void btn_addEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addEmployeeActionPerformed
        if (cmb_employeeID.getSelectedIndex() != -1) {
            try {
                String eidd = String.valueOf(cmb_employeeID.getSelectedItem());
                String name = txt_firstName.getText();
                String cnt = txt_contactNumber.getText();
                String ty = cmb_employeeType.getText();

                if (ty.equals("Main")) {
                    mainSelected = true;
                }

                tableModelEmployee.addRow(new Object[]{eidd, name, cnt, ty});
                cmb_employeeID.setSelectedIndex(-1);
                cmb_employeeID.removeItem(eidd);
                txt_firstName.setText("");
                txt_lastName.setText("");
                txt_contactNumber.setText("");
                cmb_employeeType.setText("");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error Occured.\n" + ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_btn_addEmployeeActionPerformed

    private void btn_vehicleAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vehicleAddActionPerformed
        if (cmb_vehicleNumber.getSelectedIndex() != -1) {
            try {
                String vehn = String.valueOf(cmb_vehicleNumber.getSelectedItem());
                String brr1 = txt_brand.getText();
                String brr2 = txt_model.getText();
                String brr3 = txt_vehicleType.getText();
                tableModelVehicle.addRow(new Object[]{vehn, brr1, brr2, brr3});
                cmb_vehicleNumber.setSelectedIndex(-1);
                cmb_vehicleNumber.removeItem(vehn);
                txt_brand.setText("");
                txt_model.setText("");
                txt_vehicleType.setText("");

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error Occured.\n" + ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_btn_vehicleAddActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        String delNo = txt_deliveryNumber.getText();
        String delDate = txt_date.getText();
        String status = "Pending";
        String generatedStatus = "Not Generated";
        String query2 = "";
        

        if (!lm.isEmpty()) {
            if (table_employee.getRowCount() != 0) {
                if (table_vehicle.getRowCount() != 0) {
                    try {
                      
                        statement = connection.prepareStatement("INSERT INTO delivery_header VALUES(?,?,?,?)");
                        statement.setString(1, delNo);
                        statement.setString(2, delDate);
                        statement.setString(3, status);
                        statement.setString(4, generatedStatus);
                        
                        int res = statement.executeUpdate();
                       
                        
                        int lno = lm.getSize();

                        for (int k = 0; k < lno; k++) {
                            String orderNo = String.valueOf(lm.getElementAt(k));
                            
  
                            statement = connection.prepareStatement("UPDATE orders_header SET ord_Status = 'Delivery Assigned',del_No=? WHERE ord_No=?");
                            statement.setString(1, delNo);
                            statement.setString(2,orderNo);
                            res = statement.executeUpdate();
                            
                        }

                        int rows = table_employee.getRowCount();

                        for (int i = 0; i < rows; i++) {
                            String employeeID = String.valueOf(table_employee.getValueAt(i, 0));
                            String ee = String.valueOf(table_employee.getValueAt(i, 3));
                           
                            
                            statement = connection.prepareStatement("INSERT INTO delivery_and_delivery_representative_detail VALUES(?,?)");
                            statement.setString(1, delNo);
                            statement.setString(2,employeeID);
                            res = statement.executeUpdate();
                            
                            
                            statement = connection.prepareStatement("UPDATE delivery_representative_master SET dRep_Status = 'Not Available' WHERE emp_ID=?");
                            statement.setString(1, employeeID);
                            res = statement.executeUpdate();
                        
                        }

                        int rows2 = table_vehicle.getRowCount();

                        for (int i = 0; i < rows2; i++) {
                            String vehicleID = String.valueOf(table_vehicle.getValueAt(i, 0));
                           
                          
                            statement = connection.prepareStatement("INSERT INTO delivery_and_vehicle_detail VALUES(?,?)");
                            statement.setString(1, delNo);
                            statement.setString(2,vehicleID);
                            res = statement.executeUpdate();
                           
                            
                            statement = connection.prepareStatement("UPDATE vehicle_master SET veh_Status = 'Not Available' WHERE veh_No=?");
                            statement.setString(1, vehicleID);
                            res = statement.executeUpdate();
                        
                        
                        }

                        JOptionPane.showMessageDialog(this, "Delivery Resources Successfully Assigned", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                        mainNew.getDeliveryData();
                        mainNew.getDelData();
                        mainNew.getVehData();
                        mainNew.getOrdData();
                        this.dispose();
                    } catch (HeadlessException | SQLException e) {
                        JOptionPane.showMessageDialog(this, "Error Occured.\n" + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
                        System.out.println(e);
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "No Vehicles Selected", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "No Delivery Representatives Selected", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No Orders Selected", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        txt_firstName.setText("");
        txt_lastName.setText("");
        txt_contactNumber.setText("");
        cmb_employeeType.setText("");
        txt_brand.setText("");
        txt_model.setText("");
        txt_vehicleType.setText("");
        
        int rows = table_employee.getRowCount();
        for (int i = 0; i < rows; i++) {
            String empID = String.valueOf(table_employee.getValueAt(i, 0));
            cmb_employeeID.addItem(empID);
        }
        
        rows = table_vehicle.getRowCount();
        for (int i = 0; i < rows; i++) {
            String vehNo = String.valueOf(table_vehicle.getValueAt(i, 0));
            cmb_vehicleNumber.addItem(vehNo);
        }
        
        tableModelEmployee.setRowCount(0);
        tableModelVehicle.setRowCount(0);
        
        while(!lm.isEmpty()) {
            String orderNo = lm.get(0).toString();
            cmb_orderNumber.addItem(orderNo);
            lm.remove(0);
        }
        
        cmb_orderNumber.setSelectedIndex(-1);
        cmb_employeeID.setSelectedIndex(-1);
        cmb_vehicleNumber.setSelectedIndex(-1);
    }//GEN-LAST:event_btn_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DelResoNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DelResoNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DelResoNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DelResoNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DelResoNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addEmployee;
    private javax.swing.JButton btn_addOrderNumber;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_removeEmployee;
    private javax.swing.JButton btn_removeOrderNumber;
    private javax.swing.JButton btn_removeVehicle;
    private javax.swing.JButton btn_submit;
    private javax.swing.JButton btn_vehicleAdd;
    private javax.swing.JComboBox cmb_employeeID;
    private javax.swing.JTextField cmb_employeeType;
    private javax.swing.JComboBox cmb_orderNumber;
    private javax.swing.JComboBox cmb_vehicleNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable table_employee;
    private javax.swing.JTable table_vehicle;
    private javax.swing.JTextField txt_brand;
    private javax.swing.JTextField txt_contactNumber;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_deliveryNumber;
    private javax.swing.JTextField txt_firstName;
    private javax.swing.JTextField txt_lastName;
    private javax.swing.JTextField txt_model;
    private javax.swing.JTextField txt_vehicleType;
    // End of variables declaration//GEN-END:variables
}
