/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.itfac.bit.ui;

import com.itfac.bit.database.Database;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.CMYKColor;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.draw.LineSeparator;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Invoice extends javax.swing.JFrame {

    /**
     * Creates new form Invoice
     */
    Connection con;
    Statement st1, st2, st3, st4, st5, st6, st7, st8, st9, st10;
    ResultSet rs1, rs2, rs3, rs4, rs5, rs6, rs7, rs8, rs9, rs10;
    String a, b, c, d, f, g, format, format2, ba, format3;
    DefaultTableModel modelo;
    Double ot = 0.0, del = 0.0, gt = 0.0;
    int e;
    MainNew mmm;
    DateFormat dateFormat2;
    Calendar cal2;
   
    public Invoice() {
        initComponents();
        this.setResizable(false); 
        this.setLocationRelativeTo(null);
    }

    public Invoice(MainNew mm) {
        this.setResizable(false); 
        this.setLocationRelativeTo(null);
        mmm = mm;
        initComponents();

        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        Calendar cal = Calendar.getInstance();
        txt_date.setText(dateFormat.format(cal.getTime()));
        txt_date.setEditable(false);
        dateFormat2 = new SimpleDateFormat("HH:mm:ss");
        cal2 = Calendar.getInstance();
        modelo = (DefaultTableModel) table_invoice.getModel();

        try {
            con = Database.openConnection();
            st1 = con.createStatement();
            rs1 = st1.executeQuery("SELECT inv_No FROM invoice_master");

            if (!rs1.isBeforeFirst()) {
                format = String.format("%06d", 1);
            } else {
                rs1.last();
                int invNo = rs1.getInt(1);
                invNo = invNo + 1;
                format = String.format("%06d", invNo);
            }

            txt_invoiceNumber.setText(format);
            txt_invoiceNumber.setEditable(false);

            st2 = con.createStatement();
            rs2 = st2.executeQuery("SELECT ord_No FROM orders_header WHERE ord_Status = 'Delivery Assigned' OR (del_Req = 'No' AND ord_Status = 'Placed')");

            while (rs2.next()) {
                cmb_orderNumber.addItem(rs2.getString(1));
            }

            cmb_orderNumber.setSelectedIndex(-1);
            txt_customerID.setText("");
            txt_firstName.setText("");
            txt_lastName.setText("");
            txt_addressNumber.setText("");
            txt_addressStreet.setText("");
            txt_addressCity.setText("");
            txt_deliveryAddressNumber.setText("");
            txt_deliveryAddressStreet.setText("");
            txt_deliveryAddressCity.setText("");
            txt_deliveryAddressDistrict.setText("");
            txt_contactNumber.setText("");
            txt_email.setText("");
            txt_faxNo.setText("");
            txt_orderTotal.setText("");
            txt_subTotal.setText("");
            txt_deliveryCharges.setText("");
            txt_grandTotal.setText("");
            txt_notes.setText("");
            modelo.setRowCount(0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Occured.\n" + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmb_orderNumber = new javax.swing.JComboBox();
        txt_date = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_firstName = new javax.swing.JTextField();
        txt_addressNumber = new javax.swing.JTextField();
        txt_deliveryAddressNumber = new javax.swing.JTextField();
        txt_lastName = new javax.swing.JTextField();
        txt_addressStreet = new javax.swing.JTextField();
        txt_deliveryAddressStreet = new javax.swing.JTextField();
        txt_addressCity = new javax.swing.JTextField();
        txt_deliveryAddressCity = new javax.swing.JTextField();
        txt_customerID = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_contactNumber = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_deliveryAddressDistrict = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_faxNo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_invoiceNumber = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_invoice = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        txt_orderTotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_notes = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_subTotal = new javax.swing.JTextField();
        txt_deliveryCharges = new javax.swing.JTextField();
        txt_grandTotal = new javax.swing.JTextField();
        btn_clear = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        btn_generateInvoice = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(97, 212, 179));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Invoice Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 153));
        jLabel1.setText("Order Number");

        cmb_orderNumber.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_orderNumberItemStateChanged(evt);
            }
        });

        txt_date.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 153));
        jLabel2.setText("Date");

        jPanel2.setBackground(new java.awt.Color(218, 247, 220));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 153));
        jLabel4.setText("Customer ID");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 153));
        jLabel5.setText("Name");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 102, 153));
        jLabel6.setText("Address");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 102, 153));
        jLabel7.setText("Delivery Location");

        txt_firstName.setEditable(false);

        txt_addressNumber.setEditable(false);

        txt_deliveryAddressNumber.setEditable(false);

        txt_lastName.setEditable(false);
        txt_lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lastNameActionPerformed(evt);
            }
        });

        txt_addressStreet.setEditable(false);

        txt_deliveryAddressStreet.setEditable(false);

        txt_addressCity.setEditable(false);
        txt_addressCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_addressCityActionPerformed(evt);
            }
        });

        txt_deliveryAddressCity.setEditable(false);

        txt_customerID.setEditable(false);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 102, 153));
        jLabel14.setText("Contact Number");

        txt_contactNumber.setEditable(false);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 102, 153));
        jLabel15.setText("Email");

        txt_email.setEditable(false);
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });

        txt_deliveryAddressDistrict.setEditable(false);

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 102, 153));
        jLabel16.setText("Fax");

        txt_faxNo.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_addressNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_deliveryAddressNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_firstName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_customerID, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_contactNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_deliveryAddressStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_addressStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_deliveryAddressCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txt_addressCity, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_deliveryAddressDistrict)
                    .addComponent(txt_faxNo))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_customerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_addressNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_addressStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_addressCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_deliveryAddressNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_deliveryAddressStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_deliveryAddressCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_deliveryAddressDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(txt_contactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txt_faxNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 102, 153));
        jLabel10.setText("Invoice Number");

        txt_invoiceNumber.setEditable(false);

        jPanel3.setBackground(new java.awt.Color(218, 247, 220));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Order Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        table_invoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Item Name", "Quantity", "Unit Price", "Item Total"
            }
        ));
        jScrollPane1.setViewportView(table_invoice);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 102, 153));
        jLabel12.setText("Order Total");

        txt_orderTotal.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_orderTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_orderTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 102, 153));
        jLabel8.setText("Notes");

        txt_notes.setColumns(20);
        txt_notes.setRows(5);
        jScrollPane2.setViewportView(txt_notes);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 102, 153));
        jLabel9.setText("Sub Total");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 102, 153));
        jLabel11.setText("Delivery Charges");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 102, 153));
        jLabel13.setText("Grand Total");

        txt_subTotal.setEditable(false);

        txt_deliveryCharges.setEditable(false);

        txt_grandTotal.setEditable(false);

        btn_clear.setBackground(new java.awt.Color(51, 102, 153));
        btn_clear.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_clear.setForeground(java.awt.Color.white);
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_cancel.setBackground(new java.awt.Color(255, 103, 125));
        btn_cancel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_cancel.setForeground(java.awt.Color.white);
        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_generateInvoice.setBackground(new java.awt.Color(0, 88, 50));
        btn_generateInvoice.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_generateInvoice.setForeground(java.awt.Color.white);
        btn_generateInvoice.setText("Generate Invoice");
        btn_generateInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generateInvoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_invoiceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_orderNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_deliveryCharges, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_subTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_grandTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(btn_clear)
                .addGap(61, 61, 61)
                .addComponent(btn_generateInvoice)
                .addGap(63, 63, 63)
                .addComponent(btn_cancel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_invoiceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_orderNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_subTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_deliveryCharges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_grandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_generateInvoice)
                    .addComponent(btn_cancel)
                    .addComponent(btn_clear))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_addressCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_addressCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addressCityActionPerformed

    private void txt_lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lastNameActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void cmb_orderNumberItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_orderNumberItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            txt_customerID.setText("");
            txt_firstName.setText("");
            txt_lastName.setText("");
            txt_addressNumber.setText("");
            txt_addressStreet.setText("");
            txt_addressCity.setText("");
            txt_deliveryAddressNumber.setText("");
            txt_deliveryAddressStreet.setText("");
            txt_deliveryAddressCity.setText("");
            txt_deliveryAddressDistrict.setText("");
            txt_contactNumber.setText("");
            txt_email.setText("");
            txt_faxNo.setText("");
            txt_orderTotal.setText("");
            txt_subTotal.setText("");
            txt_deliveryCharges.setText("");
            txt_grandTotal.setText("");
            modelo.setRowCount(0);
            ba = String.valueOf(cmb_orderNumber.getSelectedItem());

            try {
                st5 = con.createStatement();
                rs5 = st5.executeQuery("SELECT * FROM orders_header WHERE ord_No = '" + ba + "'");

                while (rs5.next()) {
                    String cid = rs5.getString(7);
                    st4 = con.createStatement();
                    rs4 = st4.executeQuery("SELECT * FROM customer_master WHERE cus_ID = '" + cid + "'");

                    while (rs4.next()) {
                        txt_customerID.setText(rs4.getString(1));
                        txt_firstName.setText(rs4.getString(2));
                        txt_lastName.setText(rs4.getString(3));
                        txt_addressNumber.setText(rs4.getString(4));
                        txt_addressStreet.setText(rs4.getString(5));
                        txt_addressCity.setText(rs4.getString(6));
                        txt_deliveryAddressNumber.setText(rs4.getString(7));
                        txt_deliveryAddressStreet.setText(rs4.getString(8));
                        txt_deliveryAddressCity.setText(rs4.getString(9));
                        txt_deliveryAddressDistrict.setText(rs4.getString(10));
                        txt_contactNumber.setText(String.valueOf(rs4.getInt(12)));
                        txt_email.setText(rs4.getString(11));
                        txt_faxNo.setText(String.valueOf(rs4.getInt(13)));
                    }

                    st6 = con.createStatement();
                    rs6 = st6.executeQuery("SELECT * FROM orders_details WHERE ord_No = '" + ba + "'");

                    String in = "", up = "", it = "";
                    Double upp = 0.0, ito = 0.0;
                    while (rs6.next()) {
                        String ic = rs6.getString(2);
                        st7 = con.createStatement();
                        rs7 = st7.executeQuery("SELECT * FROM item_master WHERE item_Code = '" + ic + "'");
                        if (rs7.next()) {
                            in = rs7.getString(2);
                            upp = rs7.getDouble(4);
                            up = String.valueOf(upp);
                        }

                        int qty = rs6.getInt(3);
                        ito = qty * upp;
                        it = String.valueOf(ito);
                        modelo.addRow(new Object[]{ic, in, String.valueOf(qty), up, it});
                    }

                    Double oto = rs5.getDouble(3);
                    Double gto = rs5.getDouble(4);
                    Double dch = gto - oto;

                    txt_orderTotal.setText(String.valueOf(oto));
                    txt_subTotal.setText(String.valueOf(oto));
                    txt_deliveryCharges.setText(String.valueOf(dch));
                    txt_grandTotal.setText(String.valueOf(gto));
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error Occured.\n" + ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_cmb_orderNumberItemStateChanged

    private void btn_generateInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generateInvoiceActionPerformed
        String inv = txt_invoiceNumber.getText();
        String dat = txt_date.getText();
        String tim = dateFormat2.format(cal2.getTime());
        Double tot = Double.parseDouble(txt_grandTotal.getText());
        String note = txt_notes.getText();
        String ordn = String.valueOf(cmb_orderNumber.getSelectedItem());
        String delReq = "", ordStatus = "";
        
        try {
            
            st10 = con.createStatement();
            rs10 = st10.executeQuery("SELECT del_Req FROM orders_header WHERE ord_No = '" + ordn + "'");
            
            while(rs10.next()) {
                delReq = rs10.getString(1);
            }
            
            if(delReq.equals("Yes")) {
                ordStatus = "Invoice Generated";
            } else {
                ordStatus = "Completed";
            }
            
            st8 = con.createStatement();
            st8.executeUpdate("INSERT INTO invoice_master VALUES('" + inv + "','" + dat + "','" + tim + "','" + tot + "','" + note + "','" + ordn + "')");
            st9 = con.createStatement();
            st9.executeUpdate("UPDATE orders_header SET ord_Status = '" + ordStatus + "' WHERE ord_No = '" + ordn + "'");
            JOptionPane.showMessageDialog(this, "Invoice Successfully Generated", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
            createInvoicePDF();
            mmm.getInvData();
            mmm.getOrdData();
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Occured.\n" + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }

    }//GEN-LAST:event_btn_generateInvoiceActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        cmb_orderNumber.setSelectedIndex(-1);
        txt_customerID.setText("");
        txt_firstName.setText("");
        txt_lastName.setText("");
        txt_addressNumber.setText("");
        txt_addressStreet.setText("");
        txt_addressCity.setText("");
        txt_deliveryAddressNumber.setText("");
        txt_deliveryAddressStreet.setText("");
        txt_deliveryAddressCity.setText("");
        txt_deliveryAddressDistrict.setText("");
        txt_contactNumber.setText("");
        txt_email.setText("");
        txt_faxNo.setText("");
        txt_orderTotal.setText("");
        txt_subTotal.setText("");
        txt_deliveryCharges.setText("");
        txt_grandTotal.setText("");
        txt_notes.setText("");
        modelo.setRowCount(0);
    }//GEN-LAST:event_btn_clearActionPerformed

    private void createInvoicePDF() {
        Document document = new Document();
        try {
            String invNo = txt_invoiceNumber.getText();
            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("Invoice-" + invNo + ".pdf"));
            document.open();

            //Add Image
            Image image1 = Image.getInstance(System.getProperty("user.dir") + "\\src\\com\\itfac\\bit\\companylogo.jpg");
            //Scale to new height and new width of image
            image1.scaleAbsolute(200, 100);
            //Add to document
            document.add(image1);

            Font blueFont = FontFactory.getFont(FontFactory.COURIER, 30, Font.BOLD, new CMYKColor(255, 0, 0, 0));
            document.add(new Paragraph("Invoice", blueFont));

            LineSeparator ls = new LineSeparator();
            document.add(new Chunk(ls));

            String cusID = txt_customerID.getText();
            String cusName = txt_firstName.getText() + " " + txt_lastName.getText();
            String address = txt_addressNumber.getText() + ", " + txt_addressStreet.getText() + ", " + txt_addressCity.getText();
            String delAddress = txt_deliveryAddressNumber.getText() + ", " + txt_deliveryAddressStreet.getText() + ", " + txt_deliveryAddressCity.getText() + ", " + txt_deliveryAddressDistrict.getText();
            String contact = txt_contactNumber.getText();
            String email = txt_email.getText();
            String fax = txt_faxNo.getText();
            document.add(new Paragraph("Customer ID : " + cusID));
            document.add(new Paragraph("Customer Name : " + cusName));
            document.add(new Paragraph("Address : " + address));
            document.add(new Paragraph("Delivery Address : " + delAddress));
            document.add(new Paragraph("Contact Number : " + contact));
            document.add(new Paragraph("Email : " + email));
            document.add(new Paragraph("Fax : " + fax));

            PdfPTable table = new PdfPTable(5); // 5 columns.
            table.setWidthPercentage(100); //Width 100%
            table.setSpacingBefore(20f); //Space before table
            table.setSpacingAfter(20f); //Space after table

            //Set Column widths
            float[] columnWidths = {1f, 1f, 1f, 1f, 1f};
            table.setWidths(columnWidths);

            PdfPCell cell1 = new PdfPCell(new Paragraph("Item Code"));
            cell1.setPaddingLeft(10);
            cell1.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell1.setVerticalAlignment(Element.ALIGN_LEFT);
            cell1.setFixedHeight(30f);

            PdfPCell cell2 = new PdfPCell(new Paragraph("Item Name"));
            cell2.setPaddingLeft(10);
            cell2.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell2.setVerticalAlignment(Element.ALIGN_LEFT);
            cell2.setFixedHeight(30f);

            PdfPCell cell3 = new PdfPCell(new Paragraph("Quantity"));
            cell3.setPaddingLeft(10);
            cell3.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell3.setVerticalAlignment(Element.ALIGN_LEFT);
            cell3.setFixedHeight(30f);

            PdfPCell cell4 = new PdfPCell(new Paragraph("Unit Price"));
            cell4.setPaddingLeft(10);
            cell4.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell4.setVerticalAlignment(Element.ALIGN_LEFT);
            cell4.setFixedHeight(30f);

            PdfPCell cell5 = new PdfPCell(new Paragraph("Item Total"));
            cell5.setPaddingLeft(10);
            cell5.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell5.setVerticalAlignment(Element.ALIGN_LEFT);
            cell5.setFixedHeight(30f);
            
            table.addCell(cell1);
            table.addCell(cell2);
            table.addCell(cell3);
            table.addCell(cell4);
            table.addCell(cell5);

            int rows = table_invoice.getRowCount();

            for (int i = 0; i < rows; i++) {
                String aa = String.valueOf(table_invoice.getValueAt(i, 0));
                String ab = String.valueOf(table_invoice.getValueAt(i, 1));
                String ac = String.valueOf(table_invoice.getValueAt(i, 2));
                String ad = String.valueOf(table_invoice.getValueAt(i, 3));
                String ae = String.valueOf(table_invoice.getValueAt(i, 4));

                PdfPCell cell6 = new PdfPCell(new Paragraph(aa));
                cell6.setPaddingLeft(10);
                cell6.setHorizontalAlignment(Element.ALIGN_LEFT);
                cell6.setVerticalAlignment(Element.ALIGN_LEFT);
                cell6.setFixedHeight(30f);

                PdfPCell cell7 = new PdfPCell(new Paragraph(ab));
                cell7.setPaddingLeft(10);
                cell7.setHorizontalAlignment(Element.ALIGN_LEFT);
                cell7.setVerticalAlignment(Element.ALIGN_LEFT);
                cell7.setFixedHeight(30f);
                
                PdfPCell cell8 = new PdfPCell(new Paragraph(ac));
                cell8.setPaddingLeft(10);
                cell8.setHorizontalAlignment(Element.ALIGN_LEFT);
                cell8.setVerticalAlignment(Element.ALIGN_LEFT);
                cell8.setFixedHeight(30f);

                PdfPCell cell9 = new PdfPCell(new Paragraph(ad));
                cell4.setPaddingLeft(10);
                cell4.setHorizontalAlignment(Element.ALIGN_LEFT);
                cell4.setVerticalAlignment(Element.ALIGN_LEFT);

                PdfPCell cell10 = new PdfPCell(new Paragraph(ae));
                cell10.setPaddingLeft(10);
                cell10.setHorizontalAlignment(Element.ALIGN_LEFT);
                cell10.setVerticalAlignment(Element.ALIGN_LEFT);
                cell10.setFixedHeight(30f);
                
                table.addCell(cell6);
                table.addCell(cell7);
                table.addCell(cell8);
                table.addCell(cell9);
                table.addCell(cell10);
            }

            document.add(table);

            String notes = txt_notes.getText();
            String subTotal = txt_subTotal.getText();
            String delCharge = txt_deliveryCharges.getText();
            String grandTotal = txt_grandTotal.getText();

            Paragraph p1 = new Paragraph("Invoice Notes : " + notes);
            p1.setSpacingBefore(20f);
            p1.setSpacingAfter(20f);
            document.add(p1);

            document.add(new Paragraph("Sub Total        : " + subTotal));
            document.add(new Paragraph("Delivery Charges : " + delCharge));
            document.add(new Paragraph("Grand Total      : " + grandTotal));

            document.close();
            writer.close();
            Desktop.getDesktop().open(new File("Invoice-" + invNo + ".pdf"));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Occured.\n" + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            System.out.println(e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Invoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_generateInvoice;
    private javax.swing.JComboBox cmb_orderNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_invoice;
    private javax.swing.JTextField txt_addressCity;
    private javax.swing.JTextField txt_addressNumber;
    private javax.swing.JTextField txt_addressStreet;
    private javax.swing.JTextField txt_contactNumber;
    private javax.swing.JTextField txt_customerID;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_deliveryAddressCity;
    private javax.swing.JTextField txt_deliveryAddressDistrict;
    private javax.swing.JTextField txt_deliveryAddressNumber;
    private javax.swing.JTextField txt_deliveryAddressStreet;
    private javax.swing.JTextField txt_deliveryCharges;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_faxNo;
    private javax.swing.JTextField txt_firstName;
    private javax.swing.JTextField txt_grandTotal;
    private javax.swing.JTextField txt_invoiceNumber;
    private javax.swing.JTextField txt_lastName;
    private javax.swing.JTextArea txt_notes;
    private javax.swing.JTextField txt_orderTotal;
    private javax.swing.JTextField txt_subTotal;
    // End of variables declaration//GEN-END:variables
}
