/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.itfac.bit.ui;

import com.itfac.bit.database.Database;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Order extends javax.swing.JFrame {

    /**
     * Creates new form Order
     */
    Connection con;
    Statement st1, st2, st3, st4, st5, st6;
    ResultSet rs1, rs2, rs3, rs4, rs5, rs6;
    String a, b, c, d, f, g, format, format2, ba;
    DefaultTableModel modelo;
    Double ot = 0.0, del = 0.0, gt = 0.0;
    int e;
    ButtonGroup bg;
    MainNew mmm;
    Double up = 0.0, tota1 = 0.0;
  
    public Order() {
        initComponents();
        this.setResizable(false); 
        this.setLocationRelativeTo(null);
    }

    public Order(MainNew mm) {
        mmm = mm;
        initComponents();
        this.setResizable(false); 
        this.setLocationRelativeTo(null);

        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        Calendar cal = Calendar.getInstance();
        txt_date.setText(dateFormat.format(cal.getTime()));
        txt_date.setEditable(false);

        try {
            
            con = Database.openConnection();

            st1 = con.createStatement();
            rs1 = st1.executeQuery("SELECT ord_No FROM orders_header");

            if (!rs1.isBeforeFirst()) {
                format = String.format("%06d", 1);
            } else {
                rs1.last();
                int ordNo = rs1.getInt(1);
                ordNo = ordNo + 1;
                format = String.format("%06d", ordNo);
            }

            txt_orderNumber.setText(format);
            txt_orderNumber.setEditable(false);

            st2 = con.createStatement();
            rs2 = st2.executeQuery("SELECT cus_ID FROM customer_master");

            while (rs2.next()) {
                cmb_customerID.addItem(rs2.getString(1));
            }

            st3 = con.createStatement();
            rs3 = st3.executeQuery("SELECT item_Name FROM item_master");

            while (rs3.next()) {
                cmb_itemName.addItem(rs3.getString(1));
            }

            cmb_customerID.setSelectedIndex(-1);
            cmb_itemName.setSelectedIndex(-1);
            format2 = String.format("%06d", 0);
            txt_orderTotal.setText(format2);
            txt_deliveryCharges.setText(format2);
            txt_grandTotal.setText(format2);
            txt_firstName.setText("");
            txt_lastName.setText("");
            txt_addressCity.setText("");
            txt_addressNumber.setText("");
            txt_addressStreet.setText("");
            txt_deliveryAddressNumber.setText("");
            txt_deliveryAddressStreet.setText("");
            txt_deliveryAddressCity.setText("");
            txt_deliveryAddressDistrict.setText("");
            txt_email.setText("");
            txt_faxNo.setText("");
            txt_contactNumber.setText("");
            jLabel16.setText("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error Occured.\n" + ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex);
        }

        bg = new ButtonGroup();
        bg.add(jr1);
        bg.add(jr2);
        jr2.setSelected(true);
        jr1.setEnabled(false);
        jr2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_orderNumber = new javax.swing.JTextField();
        txt_date = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmb_customerID = new javax.swing.JComboBox();
        txt_firstName = new javax.swing.JTextField();
        txt_addressNumber = new javax.swing.JTextField();
        txt_deliveryAddressNumber = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_lastName = new javax.swing.JTextField();
        txt_addressStreet = new javax.swing.JTextField();
        txt_deliveryAddressStreet = new javax.swing.JTextField();
        txt_addressCity = new javax.swing.JTextField();
        txt_deliveryAddressCity = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_contactNumber = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        txt_deliveryAddressDistrict = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_faxNo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cmb_itemName = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        txt_quantity = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_items = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txt_orderTotal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_deliveryCharges = new javax.swing.JTextField();
        txt_grandTotal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jr1 = new javax.swing.JRadioButton();
        jr2 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        btn_placeOrder = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(97, 212, 179));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Order Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 153));
        jLabel1.setText("Order Number");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 153));
        jLabel2.setText("Date");

        txt_orderNumber.setEditable(false);

        txt_date.setEditable(false);

        jPanel2.setBackground(new java.awt.Color(218, 247, 220));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(51, 102, 153));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 153));
        jLabel3.setText("Customer ID");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 153));
        jLabel4.setText("Name");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 153));
        jLabel5.setText("Address");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 102, 153));
        jLabel6.setText("Delivery Address");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 102, 153));
        jLabel7.setText("Email");

        cmb_customerID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_customerIDItemStateChanged(evt);
            }
        });
        cmb_customerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_customerIDActionPerformed(evt);
            }
        });

        txt_firstName.setEditable(false);

        txt_addressNumber.setEditable(false);

        txt_deliveryAddressNumber.setEditable(false);

        txt_email.setEditable(false);

        txt_lastName.setEditable(false);

        txt_addressStreet.setEditable(false);

        txt_deliveryAddressStreet.setEditable(false);

        txt_addressCity.setEditable(false);

        txt_deliveryAddressCity.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 102, 153));
        jLabel8.setText("Contact Number");

        btn_search.setBackground(new java.awt.Color(51, 102, 153));
        btn_search.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_search.setForeground(java.awt.Color.white);
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        txt_deliveryAddressDistrict.setEditable(false);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 102, 153));
        jLabel12.setText("Fax");

        txt_faxNo.setEditable(false);
        txt_faxNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_faxNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_faxNo)
                    .addComponent(cmb_customerID, 0, 100, Short.MAX_VALUE)
                    .addComponent(txt_firstName)
                    .addComponent(txt_addressNumber)
                    .addComponent(txt_deliveryAddressNumber)
                    .addComponent(txt_email))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_addressStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_addressCity))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_deliveryAddressStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_deliveryAddressCity))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txt_contactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_search)
                                .addGap(0, 23, Short.MAX_VALUE))
                            .addComponent(txt_deliveryAddressDistrict))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_customerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_contactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_addressNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_addressStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_addressCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_deliveryAddressNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_deliveryAddressStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_deliveryAddressCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_deliveryAddressDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_faxNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(218, 247, 220));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Order Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 102, 153));
        jLabel9.setText("Item Name");

        cmb_itemName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_itemNameItemStateChanged(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 102, 153));
        jLabel10.setText("Quantity");

        btn_add.setBackground(new java.awt.Color(0, 88, 50));
        btn_add.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_add.setForeground(java.awt.Color.white);
        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_remove.setBackground(new java.awt.Color(255, 103, 125));
        btn_remove.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_remove.setForeground(java.awt.Color.white);
        btn_remove.setText("Remove");
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });

        table_items.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Item Name", "Quantity", "Unit", "Item Total"
            }
        ));
        jScrollPane1.setViewportView(table_items);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 102, 153));
        jLabel11.setText("Order Total");

        txt_orderTotal.setEditable(false);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 102, 153));
        jLabel13.setText("Delivery Charges");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 102, 153));
        jLabel14.setText("Grand Total");

        txt_deliveryCharges.setEditable(false);
        txt_deliveryCharges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_deliveryChargesActionPerformed(evt);
            }
        });

        txt_grandTotal.setEditable(false);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 102, 153));
        jLabel15.setText("Delivery Required");

        jr1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jr1.setForeground(new java.awt.Color(51, 102, 153));
        jr1.setText("Yes");
        jr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jr1ActionPerformed(evt);
            }
        });

        jr2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jr2.setForeground(new java.awt.Color(51, 102, 153));
        jr2.setText("No");
        jr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jr2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_itemName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_remove)))
                .addGap(69, 69, 69)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jr1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jr2))
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_deliveryCharges)
                    .addComponent(txt_grandTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(txt_orderTotal))
                .addGap(91, 91, 91))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_itemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_add)
                            .addComponent(btn_remove))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel15)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jr1)
                            .addComponent(jr2)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_orderTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_deliveryCharges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txt_grandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        btn_placeOrder.setBackground(new java.awt.Color(0, 88, 50));
        btn_placeOrder.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_placeOrder.setForeground(java.awt.Color.white);
        btn_placeOrder.setText("Place Order");
        btn_placeOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_placeOrderActionPerformed(evt);
            }
        });

        btn_clear.setBackground(new java.awt.Color(51, 102, 153));
        btn_clear.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_clear.setForeground(java.awt.Color.white);
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_cancel.setBackground(new java.awt.Color(255, 103, 125));
        btn_cancel.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btn_cancel.setForeground(java.awt.Color.white);
        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_orderNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(btn_clear)
                        .addGap(79, 79, 79)
                        .addComponent(btn_placeOrder)
                        .addGap(74, 74, 74)
                        .addComponent(btn_cancel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_orderNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_clear)
                    .addComponent(btn_placeOrder)
                    .addComponent(btn_cancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_faxNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_faxNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_faxNoActionPerformed

    private void txt_deliveryChargesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_deliveryChargesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_deliveryChargesActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        String a = txt_contactNumber.getText();

        if (!a.equals("")) {
            try {
                st5 = con.createStatement();
                rs5 = st5.executeQuery("SELECT * FROM customer_master WHERE cus_Tel = '" + a + "'");

                if (rs5.next()) {
                    cmb_customerID.removeAllItems();
                    cmb_customerID.addItem(rs5.getString(1));
                    cmb_customerID.setPopupVisible(false);
                    txt_firstName.setText(rs5.getString(2));
                    txt_lastName.setText(rs5.getString(3));
                    txt_addressNumber.setText(rs5.getString(4));
                    txt_addressStreet.setText(rs5.getString(5));
                    txt_addressCity.setText(rs5.getString(6));
                    txt_deliveryAddressNumber.setText(rs5.getString(7));
                    txt_deliveryAddressStreet.setText(rs5.getString(8));
                    txt_deliveryAddressCity.setText(rs5.getString(9));
                    txt_deliveryAddressDistrict.setText(rs5.getString(10));
                    txt_email.setText(rs5.getString(11));
                    txt_faxNo.setText(String.valueOf(rs5.getInt(13)));
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error Occured.\n" + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
                System.out.println(e);
            }
            jr1.setEnabled(true);
            jr2.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "Please Enter a Contact Number", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void cmb_customerIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_customerIDItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            ba = String.valueOf(cmb_customerID.getSelectedItem());
            try {
                st4 = con.createStatement();
                rs4 = st4.executeQuery("SELECT * FROM customer_master WHERE cus_ID = '" + ba + "'");

                if (rs4.next()) {
                    txt_firstName.setText(rs4.getString(2));
                    txt_lastName.setText(rs4.getString(3));
                    txt_addressNumber.setText(rs4.getString(4));
                    txt_addressStreet.setText(rs4.getString(5));
                    txt_addressCity.setText(rs4.getString(6));
                    txt_deliveryAddressNumber.setText(rs4.getString(7));
                    txt_deliveryAddressStreet.setText(rs4.getString(8));
                    txt_deliveryAddressCity.setText(rs4.getString(9));
                    txt_deliveryAddressDistrict.setText(rs4.getString(10));
                    txt_email.setText(rs4.getString(11));
                    txt_faxNo.setText(String.valueOf(rs4.getInt(13)));
                    txt_contactNumber.setText(String.valueOf(rs4.getInt(12)));
                }
                jr1.setEnabled(true);
                jr2.setEnabled(true);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error Occured.\n" + ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_cmb_customerIDItemStateChanged

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        modelo = (DefaultTableModel) table_items.getModel();
        String in = null, ic = null, unit = null;
        

        if (cmb_itemName.getSelectedIndex() != -1) {
            try {
                st3 = con.createStatement();
                String aa = cmb_itemName.getSelectedItem().toString();
                String qtyString = txt_quantity.getText();

                if (qtyString.equals("")) {
                    JOptionPane.showMessageDialog(this, "Please Enter Quantity", "ERROR", JOptionPane.ERROR_MESSAGE);
                } else {
                    int d1 = Integer.parseInt(qtyString);
                    rs3 = st3.executeQuery("SELECT * FROM item_master WHERE item_Name = '" + aa + "'");

                    if (rs3.next()) {
                        ic = rs3.getString(1);
                        in = rs3.getString(2);
                        up = rs3.getDouble(4);
                        unit = rs3.getString(5);
                    }

                    tota1 = d1 * up;
                    modelo.addRow(new Object[]{ic, in, d1, unit, tota1});

                    ot = ot + tota1;
                    txt_orderTotal.setText(String.valueOf(ot));
                    del = Double.parseDouble(txt_deliveryCharges.getText());
                    txt_grandTotal.setText(String.valueOf(ot + del));

                    cmb_itemName.removeItem(aa);
                    cmb_itemName.setSelectedIndex(-1);
                    txt_quantity.setText("");
                    jLabel16.setText("");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error Occured.\n" + ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
                System.out.println(ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select an Item", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        if (table_items.getSelectedRow() != -1) {
            if (table_items.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Table is Empty", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                String aa = String.valueOf(table_items.getValueAt(table_items.getSelectedRow(), 4));
                double ab = Double.parseDouble(aa);
                ot = ot - ab;
                txt_grandTotal.setText(String.valueOf(ot + del));
                txt_orderTotal.setText(String.valueOf(ot));
                
                String itemName = String.valueOf(table_items.getValueAt(table_items.getSelectedRow(), 1));
                cmb_itemName.addItem(itemName);
                modelo.removeRow(table_items.getSelectedRow());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please Select a Row", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_removeActionPerformed

    private void jr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jr1ActionPerformed
        try {
            String aa = txt_deliveryAddressDistrict.getText();
            Double delch = 0.0;

            st3 = con.createStatement();
            rs3 = st3.executeQuery("SELECT del_ch FROM delivery_charges_master WHERE district = '" + aa + "'");

            if (rs3.next()) {
                delch = rs3.getDouble(1);
            }

            txt_deliveryCharges.setText(String.valueOf(delch));

            del = Double.parseDouble(txt_deliveryCharges.getText());
            txt_grandTotal.setText(String.valueOf(ot + del));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error Occured.\n" + ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex);
        }
    }//GEN-LAST:event_jr1ActionPerformed

    private void jr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jr2ActionPerformed
        txt_deliveryCharges.setText(String.format("%06d", 0));
        txt_grandTotal.setText(String.valueOf(ot));
    }//GEN-LAST:event_jr2ActionPerformed

    private void btn_placeOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_placeOrderActionPerformed
        try {
            if (cmb_customerID.getSelectedIndex() != -1) {
                if (table_items.getRowCount() != 0) {
                    String on = txt_orderNumber.getText();
                    String date = txt_date.getText();
                    String cid = cmb_customerID.getSelectedItem().toString();
                    Double ot = Double.parseDouble(txt_orderTotal.getText());
                    Double gt = Double.parseDouble(txt_grandTotal.getText());
                    String bb = "Placed";
                    String dis = txt_deliveryAddressDistrict.getText();
                    String del = "";
                    String dist = "";

                    if (jr1.isSelected()) {
                        del = jr1.getText();
                    }
                    if (jr2.isSelected()) {
                        del = jr2.getText();
                    }

                    st1 = con.createStatement();
                    rs1 = st1.executeQuery("SELECT * FROM delivery_charges_master where district = '" + dis + "'");

                    if (rs1.next()) {
                        dist = rs1.getString(1);
                    }

                    int rows = table_items.getRowCount();
                    
                    String query1 = "INSERT INTO orders_header VALUES ('" + on + "','" + date + "','" + ot + "','" + gt + "','" + del + "','" + bb + "','" + cid + "','-','" + dist + "')";

                    st2 = con.createStatement();
                    st2.executeUpdate(query1);

                    for (int i = 0; i < rows; i++) {
                        String aa = String.valueOf(table_items.getValueAt(i, 0));
                        String ab = String.valueOf(table_items.getValueAt(i, 2));
                        String query2 = "INSERT INTO orders_details VALUES('" + on + "','" + aa + "','" + ab + "')";
                        st3 = con.createStatement();
                        st3.executeUpdate(query2);

                        int qtyH = Integer.parseInt(ab);
                        st6 = con.createStatement();
                        String query3 = "UPDATE item_master SET qty_In_Hand = qty_In_Hand - '" + qtyH + "' WHERE item_Code = '" + aa + "'";
                        st6.executeUpdate(query3);
                    }

                    JOptionPane.showMessageDialog(this, "Order Successfully Placed", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    mmm.getOrdData();
                    mmm.getItemData();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Order Should Contain Atleast One Item", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "No customer has been selected", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error Occured.\n" + ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            System.out.println(ex);
        }
    }//GEN-LAST:event_btn_placeOrderActionPerformed

    private void cmb_customerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_customerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_customerIDActionPerformed

    private void cmb_itemNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_itemNameItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            try {
                st4 = con.createStatement();
                String aa = cmb_itemName.getSelectedItem().toString();
                String unit = "";

                rs4 = st4.executeQuery("SELECT * FROM item_master WHERE item_Name = '" + aa + "'");

                if (rs4.next()) {
                    unit = rs4.getString(5);
                }

                jLabel16.setText(unit);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error Occured.\n" + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_cmb_itemNameItemStateChanged

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        cmb_customerID.setSelectedIndex(-1);
        cmb_itemName.setSelectedIndex(-1);
        txt_firstName.setText("");
        txt_lastName.setText("");
        txt_addressNumber.setText("");
        txt_addressStreet.setText("");
        txt_addressCity.setText("");
        txt_deliveryAddressNumber.setText("");
        txt_deliveryAddressStreet.setText("");
        txt_deliveryAddressCity.setText("");
        txt_deliveryAddressDistrict.setText("");
        txt_email.setText("");
        txt_faxNo.setText("");
        txt_contactNumber.setText("");
        txt_quantity.setText("");
        txt_orderTotal.setText(String.format("%06d", 0));
        txt_deliveryCharges.setText(String.format("%06d", 0));
        txt_grandTotal.setText(String.format("%06d", 0));
        jr2.setSelected(true);
        jr1.setEnabled(false);
        jr2.setEnabled(false);
        
        up = 0.0;
        tota1 = 0.0;
        ot = 0.0;
        del = 0.0;
        gt = 0.0;
        
        int rows = table_items.getRowCount();
        for (int i = 0; i < rows; i++) {
            String itemName = String.valueOf(table_items.getValueAt(i, 1));
            cmb_itemName.addItem(itemName);
        }
        
        modelo.setRowCount(0);
    }//GEN-LAST:event_btn_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_placeOrder;
    private javax.swing.JButton btn_remove;
    private javax.swing.JButton btn_search;
    private javax.swing.JComboBox cmb_customerID;
    private javax.swing.JComboBox cmb_itemName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jr1;
    private javax.swing.JRadioButton jr2;
    private javax.swing.JTable table_items;
    private javax.swing.JTextField txt_addressCity;
    private javax.swing.JTextField txt_addressNumber;
    private javax.swing.JTextField txt_addressStreet;
    private javax.swing.JTextField txt_contactNumber;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_deliveryAddressCity;
    private javax.swing.JTextField txt_deliveryAddressDistrict;
    private javax.swing.JTextField txt_deliveryAddressNumber;
    private javax.swing.JTextField txt_deliveryAddressStreet;
    private javax.swing.JTextField txt_deliveryCharges;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_faxNo;
    private javax.swing.JTextField txt_firstName;
    private javax.swing.JTextField txt_grandTotal;
    private javax.swing.JTextField txt_lastName;
    private javax.swing.JTextField txt_orderNumber;
    private javax.swing.JTextField txt_orderTotal;
    private javax.swing.JTextField txt_quantity;
    // End of variables declaration//GEN-END:variables
}
